= FlashForth 5 Quick Reference for PIC and AVR Microcontrollers
Port of 2016 LaTeX document -- 2021-12-30
:toc: right
:stylesheet: ./readthedocs.css
:sectnums:
:imagesdir: ../figs
:stem: latexmath
:eqnums:


:leveloffset: +1

= Interpreter
The outer interpreter looks for words and numbers delimited by whitespace. 
Everything is interpreted as a word or a number.  
Numbers are pushed onto the stack.
Words are looked up and acted upon.
Names of words are limited to 15 characters.
Some words are compile-time use only and cannot be used interpretively.
These are noted in the result column.

= Data and the stack
The data stack (S:) is directly accessible and has 16-bit cells for holding numerical values.
Functions get their arguments from the stack and leave their results there as well.
There is also a return address stack (R:) that can be used for temporary storage.

== Notation

[cols="1,2"]
|===
| Notation        | Meaning
| `n, n1, n2, n3` | Single-cell integers (16-bit).
| `u, u1, u2`     |  Unsigned integers (16-bit).
| `x, x1, x2, x3` | Single-cell item (16-bit).
| `c`             | Character value (8-bit).
| `d ud`          | Double-cell signed and unsigned (32-bit).
| `t ut`          | Triple-cell signed and unsigned (48-bit).
| `q uq`          | Quad-cell signed and unsigned (64-bit).
| `f`             | Boolean flag: 0 is false, -1 is true.
| `flt flt1 flt3` | Floating-point value (32-bit). PIC24-30-33 only, with build option.
| `addr, addr1, addr2` | 16-bit addresses.
| `a-addr`        | cell-aligned address.
| `c-addr`        | character or byte address.
| `addr.d`        | 32-bit address.
|===

== Numbers and values

[cols="1,2"]
|===
| Code      | Result
| `2`       | Leave integer two onto the stack. `( -- 2 )`
| `#255`    | Leave decimal 255 onto the stack. `( -- 255 )`
| `%11`     | Leave integer three onto the stack. `( -- 3 )`
| `$10`     | Leave integer sixteen onto the stack. `( -- 16 )`
| `23.`     | Leave double number on the stack. `( -- 23 0 )`
| `decimal` | Set number format to base 10. `( -- )`
| `hex`     | Set number format to hexadecimal. `( -- )`
| `bin`     | Set number format to binary. `( -- )`
| `s>d`
| Sign extend single to double number. `( n -- d )` +
  Since double numbers have the most significant bits
  in the cell above the least significant bits, you can
  just `drop` the top cell to recover the single number,
  provided that the value is not too large to fit in a
  single cell.
| `d>q`
| Extend double to quad-cell number. `( d -- q )` +
  Requires `qmath.fs` to be loaded.  PIC18, PIC24-30-33.
|===

== Displaying data

[cols="1,2"]
|===
| Word   | Result
| `.`    | Display a number. `( n -- )`
| `u.`   | Display u unsigned. `( u -- )`
| `u.r`  | Display u with field width n, 0<n<256. `( u n -- )`
| `d.`   | Display double number.  `( d -- )`
| `ud.`  | Display unsigned double number. `( ud -- )`
| `.s`   | Display stack content (nondestructively).
| `.st`  | Emit status string for base, current data section, and display the stack contents. `( -- )`
| `?`    | Display content at address. `( addr -- )` PIC24-30-33
| `dump` | Display memory from address, for u bytes. `( addr u -- )`
|===


== Stack manipulation

[cols="1,2"]
|===
| Word    | Result
| `dup`   | Duplicate top item. `( x -- x x )`
| `?dup`  | Duplicate top item if nonzero. `( x -- 0 | x x )`
| `swap`  | Swap top two items. `( x1 x2 -- x2 x1 )`
| `over`  | Copy second item to top. `( x1 x2 -- x1 x2 x1 )`
| `drop`  | Discard top item. `( x -- )`
| `nip`   | Remove x1 from the stack. `( x1 x2 -- x2 )`
| `rot`   | Rotate top three items. `( x1 x2 x3 -- x2 x3 x1 )`
| `tuck`  | Insert x2 below x1 in the stack. `( x1 x2 -- x2 x1 x2 )`
| `pick`  | Duplicate the u-th item on top. `( xu ... x0 u -- xu ... x0 xu )`
| `2dup`  | Duplicate top double-cell item. `( d -- d d )`
| `2swap` | Swap top two double-cell items. `( d1 d2 -- d2 d1 )`
| `2over` | Copy second double item to top. `( d1 d2 -- d1 d2 d1 )`
| `2drop` | Discard top double-cell item. `( d -- )`
| `>r`    | Send to return stack. `S:( n -- ) R:( -- n )` _compile only_
| `r>`    | Take from return stack. `S:( -- n ) R:( n -- )` _compile only_
| `r@`    | Copy top item of return stack. `S:( -- n ) R:( n -- n )` _compile only_
| `rdrop` | Discard top item of return stack. `S:( -- ) R:( n -- )` _compile only_
| `sp@`   | Leave data stack pointer. `( -- addr )`
| `sp``   | Set the data stack pointer to address. `( addr -- )`
|===


# Operators

## Arithmetic with single-cell numbers

Some of these words require `core.fs` and `math.fs`.

[cols="1,2"]
|===
| Word      | Result
| `+`       | Add. `( n1 n2 -- n1+n2 )` sum 
| `-`       | Subtract. `( n1 n2 -- n1-n2 )` difference 
| `*`       | Multiply. `( n1 n2 -- n1*n2 )` product 
| `/`       | Divide. `( n1 n2 -- n1/n2 )` quotient 
| `mod`     | Divide. `( n1 n2 -- n.rem )` remainder 
| `/mod`    | Divide. `( n1 n2 -- n.rem n.quot )` 
| `u/`      |  Unsigned 16/16 to 16-bit division. `( u1 u2 -- u2/u1 )` 
| `u/mod`   | Unsigned division. `( u1 u2 -- u.rem u.quot )` 16-bit/16-bit to 16-bit  
| `1`       | Leave one. `( -- 1 )` 
| `1+`      | Add one. `( n -- n1 )` 
| `1-`      | Subtract one. `( n -- n1 )` 
| `2+`      | Add two.  `( n -- n1 )` 
| `2-`      | Subtract 2 from n. `( n -- n1 )` 
| `2*`      | Multiply by 2; Shift left by one bit. `( u -- u1 )` 
| `2/`      | Divide by 2; Shift right by one bit. `( u -- u1 )` 
| `*/`      | Scale. `( n1 n2 n3 -- n1*n2/n3 )` Uses 32-bit intermediate result. 
| `*/mod`   | Scale with remainder. `( n1 n2 n3 -- n.rem n.quot )` Uses 32-bit intermediate result. 
| `u*/mod`  | Unsigned Scale u1*u2/u3 `( u1 u2 u3 -- u.rem u.quot )` Uses 32-bit intermediate result. 
| `abs`     | Absolute value. `( n -- u )` 
| `negate`  | Negate n. `( n -- -n )` 
| `?negate` | Negate n1 if n2 is negative. `( n1 n2 -- n3 )` 
| `min`     | Leave minimum. `( n1 n2 -- n )` 
| `max`     | Leave maximum. `( n1 n2 -- n )` 
| `umin`    | Unsigned minimum. `( u1 u2 -- u )` 
| `umax`    | Unsigned maximum. `( u1 u2 -- u )` 
|===

## Arithmetic with double-cell numbers

Some of these words require `core.fs`, `math.fs` and `qmath.fs`.

[cols="1,2"]
|===
| Word       | Result
| `d+`       | Add double numbers. `( d1 d2 -- d1+d2 )` 
| `d-`       | Subtract double numbers. `( d1 d2 -- d1-d2 )` 
| `m+`       | Add single cell to double number.  `( d1 n -- d2 )` 
| `m*`       | Signed 16*16 to 32-bit multiply.  `( n n -- d )` 
| `d2*`      | Multiply by 2. `( d -- d )` 
| `d2/`      | Divide by 2. `( d -- d )` 
| `um*`      | Unsigned 16x16 to 32 bit multiply. `( u1 u2 -- ud )` 
| `ud*`      | Unsigned 32x16 to 32-bit multiply. `( ud u -- ud )` 
| `um/mod`   | Unsigned division. `( ud u1 -- u.rem u.quot )` 32-bit/16-bit to 16-bit 
| `ud/mod`   | Unsigned division. `( ud u1 -- u.rem ud.quot )` 32-bit/16-bit to 32-bit 
| `fm/mod`   | Floored division. `( d n -- n.rem n.quot )` 
| `sm/rem`   | Symmetric division. `( d n -- n.rem n.quot )` 32-bit/16-bit to 16-bit. 
| `m*/`      | Scale with triple intermediate result. `d2 = d1*n1/n2` `( d1 n1 n2 -- d2 )` 
| `um*/`     | Scale with triple intermediate result. `ud2 = ud1*u1/u2` `( ud1 u1 u2 -- ud2)` 
| `dabs`     | Absolute value. `( d -- ud )` 
| `dnegate`  | Negate double number. `( d -- -d )` 
| `?dnegate` | Negate d if n is negative. `( d n -- -d )` 
|===

## Arithmetic with triple- and quad-numbers

For PIC18, these words require `core.fs`, `math.fs` and `qmath.fs`.

[cols="1,2"]
|===
| Word     | Result
| `q+`     | Add a quad to a quad. `( q1 q2 -- q3 )` For PIC24-30-33. 
| `qm+`    | Add double to a quad. `( q1 d -- q2 )` For PIC18 and PIC24-30-33. 
| `uq*`    | Unsigned 32x32 to 64-bit multiply. `( ud ud -- uq )` For PIC18 and PIC24-30-33. 
| `ut*`    | Unsigned 32x16 to 48-bit multiply. `( ud u -- ut )` 
| `ut/`    | Divide triple by single. `( ut u -- ud )` 
| `uq/mod` | Divide quad by double. `( uq ud -- ud-rem ud-quot )` 
|===

## Relational

[cols="1,2"]
|===
| Word     | Result
| `=`      | Leave true if x1 x2 are equal. `( x1 x2 -- f )` 
| `<>`     |  Leave true if x1 x2 are not equal. `( x1 x2 -- f )` 
| `<`      |  Leave true if n1 less than n2. `( n1 n2 -- f )` 
| `>`      |  Leave true if n1 greater than n2. `( n1 n2 -- f )` 
| `0=`     |  Leave true if n is zero. `( n -- f )` Inverts logical value. 
| `0<`     |  Leave true if n is negative. `( n -- f )` 
// | `0>`  |  Leave true if n is positive. `( n -- f )` 
| `within` | Leave true if xl <= x < xh. `( x xl xh -- f )` 
| `u<`     | Leave true if u1 < u2. `( u1 u2 -- f )` 
| `u>`     | Leave true if u1 > u2. `( u1 u2 -- f )` 
| `d=`     | Leave true if d1 d2 are equal. `( d1 d2 -- f )` 
| `d0=`    | Leave true if d is zero. `( d -- f )` 
| `d0<`    | Leave true if d is negative. `( d -- f )` 
| `d<`     | Leave true if d1 < d2. `( d1 d2 -- f )` 
| `d>`     | Leave true if d1 > d2. `( d1 d2 -- f )` 
|===

## Bitwise

[cols="1,2"]
|===
| Word      | Result
| `invert`  | Ones complement. `( x -- x )` 
| `dinvert` | Invert double number.  `( du -- du )` 
| `and`     | Bitwise and. `( x1 x2 -- x )` 
| `or`      | Bitwise or. `( x1 x2 -- x )` 
| `xor`     | Bitwise exclusive-or. `( x -- x )` 
| `lshift`  | Left shift by u bits. `( x1 u -- x2 )` 
| `rshift`  | Right shift by u bits. `( x1 u -- x2 )` 
|===

# Memory

Typically, the microcontroller has three distinct memory contexts: 
Flash, EEPROM and SRAM.
FlashForth unifies these memory spaces into a single 64kB address space.

## PIC18 Memory map

The address ranges are:
[cols="1,2"]
|===
| Range    | Use
| `$0000` -- `$ebff` | Flash 
| `$ec00` -- `$efff` | EEPROM 
| `$f000` -- `$ff5f` | SRAM, general use 
| `$ff60` -- `$ffff` | SRAM, special function registers  
|===

The high memory mark for each context will depend on the particular device used.
Using a PIC18F26K22 and the default values in `p18f-main.cfg` 
for the UART version of FF, a total of 423 bytes is dedicated to the FF system.
The rest (3473 bytes) is free for application use. 
Also, the full 64kB of Flash memory is truncated to fit within the
range specified above.

## PIC24 Memory map

A device with EEPROM will have its 64kB address space divided into:
[cols="1,2"]
|===
| Range                          | Use
| `$0000` -- `$07ff`             | SRAM, special function registers 
| `$0800` -- `($0800+RAMSIZE-1)` | SRAM, general use
| `($0800+RAMSIZE)` -- `$fbff`   | Flash 
| `$fc00` -- `$ffff`             | EEPROM  
|===
The high memory mark for the Flash context will depend on the device.
Also, the full Flash memory of the device may not be accessible.

## AVR8 Memory map
All operations are restricted to 64kB byte address space that is divided into:
[cols="1,2"]
|===
| Range                                 | Use
| `$0000` -- `(RAMSIZE-1)`              | SRAM 
| `RAMSIZE` -- `(RAMSIZE+EEPROMSIZE-1)` | EEPROM 
| `($ffff-FLASHSIZE+1)` -- `$ffff`      | Flash  
|===
The SRAM space includes the IO-space and special function registers.
The high memory mark for the Flash context is set by the combined size
of the boot area and FF kernel.

## Memory Context

[cols="1,2"]
|===
| Word     | Result
| `ram`    | Set address context to SRAM. `( -- )` 
| `eeprom` | Set address context to EEPROM. `( -- )` 
| `flash`  | Set address context to Flash. `( -- )` 
| `fl-`    | Disable writes to Flash, EEPROM. `( -- )` 
| `fl+`    | Enable writes to Flash, EEPROM, default. `( -- )` 
| `iflush` | Flush the flash write buffer. `( -- )` 
// | `lock` | Disable writes to Flash, EEPROM. `( -- )` 
| `here`   | Leave the current data section dictionary pointer. `( -- addr )` 
| `align`  | Align the current data section dictionary pointer to cell boundary. `( -- )` 
| `hi`     | Leave the high limit of the current data space. `( -- u )` 
|===


## Accessing Memory

[cols="1,2"]
|===
| Word  | Result
| `!`   | Store x to address. `( x a-addr -- )` 
| `@`   | Fetch from address. `( a-addr -- x )` 
| `@+`  | Fetch cell and increment address by cell size. `( a-addr1 -- a-addr2 x )`
| `2!`  | Store 2 cells to address. `( x1 x2 a-addr -- )` 
| `2@`  | Fetch 2 cells from address. `( a-addr -- x1 x2 )` 
| `c!`  | Store character to address. `( c addr -- )` 
| `c@`  | Fetch character from address. `( addr -- c )` 
| `c@+` | Fetch char, increment address. `( addr1 -- addr2 c )` 
| `+!`  | Add n to cell at address. `( n addr -- )` 
| `-@`  | Fetch from addr and decrement addr by 2. `( addr1 -- addr2 x )` 
| `>a`  | Write to the A register. `( x -- )`
| `a>`  | Read from the A register. `( -- x )`
|===

## Accessing Extended (Flash) Memory
[cols="1,2"]
|===
| Word  | Result
| `x!`  | Store u to real flash address. `( u addr.d -- )` PIC18, AVR8 
| `x!`  | Store u to real flash address. `( ud addr.d -- )` PIC24-30-33 
| `x@`  | Fetch from real flash address. `( addr.d -- u )` PIC18, AVR8 
| `x@`  | Fetch from real flash address. `( addr.d -- ud )` PIC24-30-33 
|===

## Accessing bits in RAM
[cols="1,2"]
|===
| Word    | Result
| `mset`  | Set bits in file register with mask c. `( c addr -- )` For PIC24-30-33, the mask is 16 bits. 
| `mclr`  | Clear bits in file register with mask c. `( c addr -- )` 
| `mtst`  | AND file register byte with mask c. `( c addr -- x )` 
|===

The following come from `bit.fs`
[cols="1,2"]
|===
| `bit1:` _name_ | Define a word to set a bit. `( addr bit -- )` 
| `bit0:` _name_ | Define a word to clear a bit. `( addr bit -- )` 
| `bit?:` _name_ | Define a word to test a bit. `( addr bit -- )` +
                   When executed, _name_ leaves a flag. `( -- f )` 
|===

# The Dictionary

## Dictionary management

[cols="1,2"]
|===
| Code                  | Result
| `marker -my-mark`     | Mark the dictionary and memory allocation state with `-my-mark`. 
| `-my-mark`            | Return to the dictionary and allotted-memory state that existed before `-my-mark` was created. 
| `find` _name_         | Find name in dictionary. `( -- n )` 
|                       | Leave 1 immediate, -1 normal, 0 not found. 
| `forget` _name_       | Forget dictionary entries back to _name_. 
| `empty`               | Reset all dictionary and allotted-memory pointers. `( -- )` 
| `words`               | List all words in dictionary. `( -- )` 
| `words` _xxx_         | List words containing _xxx_. `( -- )` 
|===


## Defining constants and variables

[cols="1,2"]
|===
| Code                 | Result
| `constant` _name_    | Define new constant. `( n -- )`  
| `2constant` _name_   | Define double constant. `( x x -- )` 
| _name_               | Leave value on stack. `( -- n )` 
| `variable` _varname_ | Define a variable in the current data section. `( -- )` + 
                         Use `ram`, `eeprom` or `flash` to set data section. 
| `2variable` _name_   | Define double variable. `( -- )` 
| _varname_            | Leave address on stack.  `( -- addr )` 
| `value` _valname_    | Define value. `( n -- )` 
| `to` _valname_       | Assign new value to _valname_. `( n -- )` 
| _valname_            | Leave value on stack.  `( -- n )` 
| `user` _name_        | Define a user variable at offset `+n`. `( +n -- )` 
|===

## Examples

[cols="1,2"]
|===
| Code                    | Result
| `ram`                   | Set SRAM context for variables and values.
                            Be careful not to accidentally define variables in EEPROM or Flash memory.
                            That memory wears quickly with multiple writes. 
| `$ff81 constant portb`  | Define constant in Flash. 
| `3 value xx`            | Define value in SRAM. 
| `variable yy`           | Define variable in SRAM. 
| `6 yy !`                | Store 6 in variable `yy`. 
| `eeprom 5 value zz ram` | Define value in EEPROM. 
| `xx yy zz portb yy @`   | Leaves `3 f172 5 ff81 6` on stack. 
| `warm`                  | Warm restart clears SRAM data. 
| `xx yy zz portb yy @`   | Leaves `0 f172 5 ff81 0` on stack. 
| `4 to xx`               | Sets new value.  
| `xx yy zz portb yy @`   | Leaves `4 f172 5 ff81 0` on stack. 
| `hi here - u.`          | Prints the number of bytes free. 
| `$ff8a constant latb`   | PortB latch for the PIC18. 
| `$ff93 constant trisb`  | PortB direction-control register. 
| `%00000010 trisb mclr`  | Sets RB1 as output.  
| `latb 1 bit1: pb1-high` | Defines a word to set RB1 high. 
| `pb1-high`              | Sets RB1 high. 
|===

## Defining compound data objects

[cols="1,2"]
|===
| Code            | Result
| `create` _name_ | Create a word definition and store the current data section pointer. 
| `does>`         | Define the runtime action of a created word. _compile only_
| `allot`         | Advance the current data section dictionary pointer by u bytes. `( u -- )` 
| `,`             | Append x to the current data section. `( x -- )` 
| `c,`            | Append c to the current data section. `( c -- )` 
| `,"` _xxx_ `"`  | Append a string at HERE. `( -- )` 
| `i,`            | Append x to the flash data section. `( x -- )` 
| `ic,`           | Append c to the flash data section. `( c -- )` 
| `cf,`           | Compile xt into the flash dictionary. `( addr -- )` 
| `c>n`           | Convert code field addr to name field addr. `( addr1 -- addr2 )` 
| `n>c`           | Convert name field addr to code field addr. `( addr1 -- addr2 )` 
| `n>l`           | Convert `nfa` to `lfa`. `( nfa -- lfa )` Not implemented; use 2-! instead. 
| `>body`         | Leave the parameter field address of the created word. `( xt -- a-addr )` 
| `:noname`       | Define headerless forth code. `( -- addr )` 
| `>xa`           | Convert a Flash virtual address to a real executable address. `( a-addr1 -- a-addr2 )` PIC24-30-33, ATmega 
| `xa>`           | Convert a real executable address to a Flash virtual address. `( a-addr1 -- a-addr2 )` PIC24-30-33, ATmega 
|=== 

## Array examples

[cols="2a,3"]
|===
| Code                         | Comments

| 
----
ram
----
| We want these arrays made in RAM memory.  

|
----
create my-array 20 allot
my-array 20 $ff fill
my-array 20 dump
----
| Create an array, fill it with 1s, and display its content.

|
----
create my-cell-array
  100 , 340 , 5 , 
----
| Initialise an array of cells.

|
----
my-cell-array 2 cells + @
----
| Should leave 5. `( -- x )` 

|
----
create my-byte-array 
  18 c, 21 c, 255 c,
----
| Initialised an array of bytes. 

|
----
my-byte-array 2 chars + c@
----
| Should leave 255. `( -- c )` 

|
----
: mk-byte-array
    create allot
    does> + ;
----
| Make our own defining word to make byte array objects, as shown in the FF User's Guide.

|
----
10 mk-byte-array my-bytes
----
| Creates an array object my-bytes, which has stack effect `( n -- addr )`.
 
|
----
18 0 my-bytes c!
----
| Sets an element. The execution `0 my-bytes` leaves the address of the first byte element on the stack.
  The execution of `c!` results in the number `18` being stored at that address.
 
|
----
21 1 my-bytes c!
----
| Sets another.

|
----
255 2 my-bytes c!
----
| And another.
 
|
----
2 my-bytes c@
----
| Should leave 255. The execution of `2 my-bytes` leaves the address of the third byte element on the stack.
  The execution of `c@` fetches the byte at that address.

|
----
: mk-cell-array
    create cells allot 
    does> swap cells + ;
----
| Make a defining word, this time to make cell array objects.
  Its stack effect is `( n -- )`

|
----
5 mk-cell-array my-cells
----
| Creates an array object `my-cells` whose stack effect is `( n -- addr )`.

|
----
3000 0 my-cells !
----
| Sets an element.
 
|
----
45000 1 my-cells !
----
| ...and another.

|
----
63000 2 my-cells !
----
| ...and another.
 
|
----
1 my-cells @ .
----
| Should print `45000` 
|===

## Memory operations

Some of these words come from `core.fs`.

[cols="1,2"]
|===
| Word        | Result
| `cmove`     | Move `u` bytes from address-1 to address-2. `( addr1 addr2 u -- )` +
                Copy proceeds from low address to high address. 
| `wmove`     | Move u cells from address-1 to address-2. `( addr1 addr2 u -- )` PIC24-30-33 only 
| `fill`      | Fill u bytes with c starting at address. `( addr u c -- )` 
| `erase`     | Fill u bytes with 0 starting at address. `( addr u -- )` 
| `blanks`    | Fill u bytes with spaces starting at address. `( addr u -- )` 
| `cells`     | Convert cells to address units. `( u -- u )` 
| `chars`     | Convert chars to address units. `( u -- u )` 
| `char+`     | Add one to address. `( addr1 -- addr2 )` 
| `cell+`     | Add size of cell to address. `( addr1 -- addr2 )` 
| `aligned`   | Align address to a cell boundary. `( addr -- a-addr )` 
|===

## Predefined constants

\begin{tabular}{@{}ll@{}}
\verb!cell!  & Size of one cell in characters. \verb!( -- n )! \\
\verb!true!  & Boolean true value. \verb!( -- -1 )! \\
\verb!false!  & Boolean false value. \verb!( -- 0 )! \\
\verb!bl!  & ASCII space. \verb!( -- c )! \\
\verb!Fcy!  & Leave the cpu instruction-cycle frequency in kHz.  \verb!( -- u )! \\
\verb!ti#!  & Size of the terminal input buffer. \verb!( -- u )! \\
\end{tabular}

## Predefined variables

\begin{tabular}{@{}ll@{}}
\verb!base!  & Variable containing number base. \verb!( -- a-addr )! \\
\verb!irq!  & Interrupt vector (SRAM variable). \verb!( -- a-addr )! \\
            & Always disable user interrupts and clear \\
            & related interrupt enable bits before zeroing \\
            & interrupt vector. \\
            & \verb!di false to irq ei! \\
\verb!turnkey!  & Vector for user start-up word. \verb!( -- a-addr )! \\
                & EEPROM value mirrored in SRAM. \\
\verb!prompt!  & Deferred execution vector for the info displayed \\
               & by quit. Default value is \verb!.st! \verb!( -- a-addr )! \\
\verb!'emit!  & EMIT vector.  Default is \verb!tx1! \verb!( -- a-addr )! \\
\verb!'key!  & KEY vector.  Default is \verb!rx1! \verb!( -- a-addr )! \\
\verb!'key?!  & KEY? vector.  Default is \verb!rx1?!  \verb!( -- a-addr )! \\
\verb!'source!  & Current input source. \verb!( -- a-addr )! \\
% \verb!latest!  & Holds the address of the latest defined word. \\  % cannot fit in 4 pages
%                & \verb!( -- a-addr )! \\
\verb!s0!   & Variable for start of data stack. \verb!( -- a-addr )! \\
\verb!r0!   & Bottom of return stack. \verb!( -- a-addr )! \\
\verb!rcnt! & Number of saved return stack cells. \verb!( -- a-addr )! \\
\verb!tib!  & Address of the terminal input buffer. \verb!( -- a-addr )! \\
\verb!tiu!  & Terminal input buffer pointer. \verb!( -- a-addr )! \\
\verb!>in!  & Variable containing the offset, in characters, \\
            & from the start of \verb!tib! to the current \\
            & parse area. \verb!( -- a-addr )! \\
\verb!pad!  & Address of the temporary area for strings. \verb!( -- addr )! \\
            & \verb!: pad tib ti# + ;! \\
            % & pad is \verb!ram here $20 +! \\
            & Each task has its own pad but has zero default size. \\
            & If needed the user must allocate it separately \\
            & with allot for each task. \\
\verb!dp!   & Leave the address of the current data section \\
            & dictionary pointer. \verb!( -- addr )! \\
            & EEPROM variable mirrored in RAM. \\
\verb!dps!  & End address of dictionary pointers. \verb!( -- d )! \\
            & Absolute address of start of free Flash. \\
            & Library and C code can be linked, \\
            & starting at this address.  PIC24, dsPIC33 \\
\verb!hp!   & Hold pointer for formatted numeric output.\\
            & \verb!( -- a-addr )! \\
\verb!up!   & Variable holding a user pointer. \verb!( -- addr )!\\
\verb!latest! & Variable holding the address of the latest \\
              & defined word. \verb!( -- a-addr )! \\
\verb!float?! & Interpreter defer for parsing floating-point values.\\
              & \verb!' >float is float?! \\
              & PIC24-30-33 only \\
\end{tabular}

# Floating-point for PIC24-30-33

These words require that FlashForth has been built with the \verb!.eq FLOATS, 1! option
in the relevant processor config file.\\
\begin{tabular}{@{}ll@{}}
\verb!>float! & Convert a string into a float. \verb!( c-addr u -- flt f )! \\
              & Note that it works for decimal base only. \\
              & Examples: \verb!1e10! \verb!-1e10! \verb!1.234e10! \verb!-1.234e10! \\
\verb!f.! & Print in decimal format. \verb!( flt -- )! \\
\verb!fe.! & Print in engineering format. \verb!( flt -- )! \\
\verb!fs.! & Print in scientific format. \verb!( flt -- )! \\
\verb!fdrop! & Discard top float item. \verb!( flt -- )! \\
\verb!fdup! & Duplicate top float item. \verb!( flt -- flt flt )! \\
\verb!fover! & Copy second float item to top. \\
             & \verb!( flt1 flt2 -- flt1 flt2 flt1 )! \\
\verb!fswap! & Swap top two float items. \verb!( flt1 flt2 -- flt2 flt1 )! \\
\verb!frot! & Rotate top three float items. \\
            & \verb!( flt1 flt2 flt3 -- flt2 flt3 flt1 )! \\
\verb!fnip! & Remove second top float. \verb!( flt1 flt2 -- flt2 )! \\
\verb!ftuck! & Insert \verb!flt2! below \verb!flt1!. \\
             & \verb!( flt1 flt2 -- flt2 flt1 flt2 )! \\
\verb!nfswap! & Swap float and single. \verb!( flt n -- n flt )! \\
\verb!fnswap! & Swap float and single. \verb!( n flt -- flt n )! \\
\verb!nfover! & Copy float item over single. \verb!( flt n -- flt n flt )! \\
\verb!fnover! & Copy single over float item. \verb!( n flt -- n flt n)! \\
\verb!f@! & Fetch float item to stack. \verb!( addr -- flt )! \\
\verb!f!! & Store float item to address. \verb!( flt addr -- )! \\
\verb!fconstant! \textit{name} & Define constant. \verb!( flt -- )! \\
\verb!fvariable! \textit{name} & Define variable. \verb!( -- )! \\
\verb!fliteral! & Compile in literal value. \verb!( flt -- )! \\
\verb!f0! & Leave value 0.0 on stack. \verb!( -- flt )! \\
\verb!f1! & Leave value 1.0 on stack. \verb!( -- flt )! \\
\verb!f10! & Leave value 10.0 on stack. \verb!( -- flt )! \\
\verb!f0.5! & Leave value 0.5 on stack. \verb!( -- flt )! \\
\verb!s>f! & Convert single to float. \verb!( n -- flt )! \\
\verb!d>f! & Convert double to float. \verb!( d -- flt )! \\
\verb!f>s! & Convert float to single. \verb!( flt -- n )! \\
\verb!f>d! & Convert float to double. \verb!( flt -- d )! \\
\verb!f0=! & Leave \verb!true! if \verb!flt! equal to zero. \verb!( flt -- f )! \\
\verb!f0<! & Leave \verb!true! if \verb!flt! less than zero. \verb!( flt -- f )! \\
\verb!f=! & Leave \verb!true! if floats are equal. \verb!( flt1 flt2 -- f )! \\
\verb!f<! & Leave \verb!true! if \verb!flt1! less than \verb!flt2!. \verb!( flt1 flt2 -- f )! \\
\verb!f<=! & eave \verb!true! if \verb!flt1! less than or equal to \verb!flt2!. \\
           & \verb!( flt1 flt2 -- f )! \\
\verb!f>! & Leave \verb!true! if \verb!flt1! greater than \verb!flt2!. \\
          & \verb!( flt1 flt2 -- f )! \\
\verb!f>=! & Leave \verb!true! if \verb!flt1! greater than or equal to \verb!flt2!. \\
           & \verb!( flt1 flt2 -- f )! \\
\verb!fnegate! & Negate float value. \verb!( flt -- -flt )! \\
\verb!fabs! & Leave absolute value. \verb!( flt1 -- flt2 )! \\
\verb!fround! & Round to nearest integral value. \verb!( flt1 -- flt2 )! \\
\verb!fmin! & Leave minimum. \verb!( flt1 flt2 -- flt )! \\
\verb!fmax! & Leave maximum. \verb!( flt1 flt2 -- flt )! \\
\verb!f2*! & Multiple by 2. \verb!( flt -- flt*2)! \\
\verb!f2/! & Divide by 2. \verb!( flt -- flt/2 )! \\
\end{tabular}\\

The following functions call out to the Microchip math library.\\
\begin{tabular}{@{}ll@{}}
\verb!f+! & Addition \verb!( flt1 flt2 -- flt1+flt2 )! \\
\verb!f-! & Subtraction \verb!( flt1 flt2 -- flt1-flt2 )! \\
\verb!f*! & Multiplication \verb!( flt1 flt2 -- flt1*flt2 )! \\
\verb!f/! & Division \verb!( flt1 flt2 -- flt1/flt2 )! \\
\verb!fpow! & Power. \verb!( flt1 flt2 -- flt1**flt2)! \\
\verb!fsin! & Sine of \verb!flt! in radians. \verb!( flt -- sin(flt) )! \\
\verb!fcos! & Cosine of \verb!flt! in radians. \verb!( flt -- cos(flt) )! \\
\verb!ftan! & Tangent of \verb!flt! in radians. \verb!( flt -- tan(flt) )! \\
\verb!fasin! & Arcine of \verb!flt!, radians. \verb!( flt -- asin(flt) )! \\
\verb!facos! & Arccosine of \verb!flt!, radians. \verb!( flt -- acos(flt) )! \\
\verb!fatan! & Arctangent of \verb!flt!, radians. \verb!( flt -- atan(flt) )! \\
\verb!fatan2! & Arctangent of \verb!flt1/flt2!, radians. \\
              & \verb!( flt1 flt2 -- atan(flt1/flt2) )! \\
\verb!fsqrt! & Square-root. \verb!( flt -- sqrt(flt) )! \\
\verb!fexp! & Exponential. \verb!( flt -- exp(flt) )! \\
\verb!flog! & Natural logarithm. \verb!( flt -- loge(flt) )! \\
\verb!flog10! & Logarithm, base 10. \verb!( flt -- log10(flt) )! \\
\verb!fcosh! & Hyperbolic cosine. \verb!( flt -- cosh(flt) )! \\
\verb!fsinh! & Hyperbolic sine. \verb!( flt -- sinh(flt) )! \\
\verb!ftanh! & Hyperbolic tangent. \verb!( flt -- tanh(flt) )! \\
\end{tabular}\\

# The Compiler

## Defining functions

\begin{tabular}{@{}ll@{}}
\verb!:!  & Begin colon definition. \verb!( -- )! \\
{\compileonly\verb!;!}  & End colon definition.  \verb!( -- )! \\
\verb![!  & Enter interpreter state. \verb!( -- )! \\
\verb!]!  & Enter compilation state. \verb!( -- )! \\
\verb!state! & Compilation state. \verb!( -- f )! \\
             & State can only be changed with \verb![! and \verb!]!. \\
\end{tabular} \\
\begin{tabular}{@{}ll@{}}
{\compileonly\verb![i!}  & Enter Forth interrupt context. \verb!( -- )! \\
                         & PIC18, PIC24-30-33 \\
{\compileonly\verb!i]!}  & Enter compilation state. \verb!( -- )! \\
                         & PIC18, PIC24-30-33 \\
{\compileonly\verb!;i!}  & End an interrupt word. \verb!( -- )! \\
\end{tabular} \\
\begin{tabular}{@{}ll@{}}
\verb!literal! & Compile value on stack at compile time. \verb!( x -- )! \\
               & At run time, leave value on stack. \verb!( -- x )! \\
\verb!2literal! & Compile double value on stack at compile time. \\
                &\verb!( x x -- )! \\
                & At run time, leave value on stack. \verb!( -- x x )! \\
\verb!inline! \textit{name} & Inline the following word. \verb!( -- )! \\
\verb!inlined!  & Mark the last compiled word as inlined. \verb!( -- )! \\
\verb!immediate!  & Mark latest definition as immediate. \verb!( -- )! \\
\verb!immed?! & Leave a nonzero value if addr contains \\
              & an immediate flag. \verb!( addr -- f )! \\
\verb!in?! & Leave a nonzero flag if \verb!nfa! has inline bit \\
           & set.  \verb!( nfa -- f )! \\
{\compileonly\verb!postpone!} \textit{name} & Postpone action of immediate word. \verb!( -- )! \\
\verb!see !\textit{name}  & Show definition. Load \verb!see.txt!. \\
\end{tabular}

## Comments

\begin{tabular}{@{}ll@{}}
\verb!( !\textit{comment text}\verb!)!   & Inline comment. \\
\verb!\ !\textit{comment text}  & Skip rest of line. \\
\end{tabular}

## Examples of colon definitions

\begin{tabular}{@{}ll@{}}
\verb!: square ( n -- n**2 )!   & Example with stack comment. \\
\verb!  dup * ;!                & ...body of definition. \\
\verb!: poke0  ( -- )!          & Example of using PIC18 assembler. \\
\verb!  [ $f8a 0 a, bsf, ] ; !  &  \\
\end{tabular}

# Flow control

## Structured flow control
\begin{tabular}{@{}ll@{}}
{\compileonly\verb!if!} \textit{xxx} {\compileonly\verb!else!} \textit{yyy} {\compileonly\verb!then!} & Conditional execution. \verb!( f -- )! \\
{\compileonly\verb!begin!} \textit{xxx} {\compileonly\verb!again!} & Infinite loop. \verb!( -- )! \\
{\compileonly\verb!begin!} \textit{xxx} \textit{cond} {\compileonly\verb!until!} & Loop until \textit{cond} is true. \verb!( -- )! \\
{\compileonly\verb!begin!} \textit{xxx} \textit{cond} {\compileonly\verb!while!}  &  Loop while \textit{cond} is true. \verb!( -- )! \\
\verb!     ! \textit{yyy} {\compileonly\verb!repeat!}               & \textit{yyy} is not executed on the last iteration. \\
{\compileonly\verb!for!} \textit{xxx} {\compileonly\verb!next!}  & Loop u times. \verb!( u -- )! \\
                                     & {\compileonly\verb!r@!} gets the loop counter  u-1 ... 0 \\
{\compileonly\verb!endit!}  & Sets loop counter to zero so that we leave \\
              & a {\compileonly\verb!for!} loop when {\compileonly\verb!next!} is encountered. \\
              & \verb!( -- )! \\
\end{tabular}\\
From \verb!doloop.txt!, we get the ANSI loop constructs which iterate from \textit{initial}
up to, but not including, \textit{limit}:\\
\begin{tabular}{@{}ll@{}}
\textit{limit} \textit{initial} {\compileonly\verb!do!} \textit{words-to-repeat} {\compileonly\verb!loop!} & \\
\textit{limit} \textit{initial} {\compileonly\verb!do!} \textit{words-to-repeat} \textit{value} {\compileonly\verb!+loop!} & \\
\end{tabular}\\ 
\begin{tabular}{@{}ll@{}}
{\compileonly\verb!i!} & Leave the current loop index. \verb!( -- n )! \\
         & Innermost loop, for nested loops. \\
{\compileonly\verb!j!} & Leave the next-outer loop index. \verb!( -- n )! \\
{\compileonly\verb!leave!} & Leave the do loop immediately. \verb!( -- )! \\
{\compileonly\verb!?do!} & Starts a do loop which is not run if \\
                         & the arguments are equal. \verb!( limit initial -- )! \\
\end{tabular}\\ 

## Loop examples

\begin{tabular}{@{}ll@{}}
\verb!decimal! & \\
\verb!: sumdo 0 100 0 do i + loop ;! & \verb!sumdo! leaves 4950 \\
\verb!: sumfor 0 100 for r@ + next ;! & \verb!sumfor! leaves 4950 \\
\verb!: print-twos 10 0 do i u. 2 +loop ;! & \\
\end{tabular}\\

## Case example
From \verb!case.txt!, we get words {\compileonly\verb!case!}, {\compileonly\verb!of!}, 
{\compileonly\verb!endof!}, {\compileonly\verb!default!} and {\compileonly\verb!endcase!}
to define case constructs.\\
\begin{tabular}{@{}ll@{}}
\verb!: testcase! & \\
\verb!  4 for r@! & \\
\verb!    case! & \\
\verb!      0 of ." zero " endof! & \\
\verb!      1 of ." one " endof! & \\
\verb!      2 of ." two " endof! & \\
\verb!      default ." default " endof! & \\
\verb!    endcase! & \\
\verb!  next ! & \\
\verb!;! & \\
\end{tabular}\\


## Unstructured flow control
\begin{tabular}{@{}ll@{}}
\verb!exit!  & Exit from a word. \verb!( -- )! \\
             & If exiting from within a for loop, \\
             & we must drop the loop count with \verb!rdrop!. \\
\verb!abort! & Reset stack pointer and execute quit. \verb!( -- )! \\
\verb!?abort!  & If flag is false, print message \\
               & and abort. \verb!( f addr u -- )! \\
\verb!?abort?!  & If flag is false, output ? and abort. \verb!( f -- )! \\
{\compileonly\verb!abort"!}\verb! xxx"!  & if flag is false, type out last word executed, \\
		    & followed by text xxx. \verb!( f -- )! \\
\verb!quit!  & Interpret from keyboard. \verb!( -- )! \\
\end{tabular}\\
\begin{tabular}{@{}ll@{}}
\verb!warm!  & Make a warm start. \\
             & Reset reason will be displayed on restart.\\
             & \verb!S!: Reset instruction\\
             & \verb!E!: External reset pin\\
             & \verb!W!: Watchdog reset\\
             & \verb!U!: Return stack underflow\\
             & \verb!O!: Return stack overflow\\
             & \verb!B!: Brown out reset\\
             & \verb!P!: Power on reset\\
             & \verb!M!: Math error\\
             & \verb!A!: Address error\\ 
             & Note that irq vector is cleared. \\
\end{tabular}


## Vectored execution (Function pointers)

\begin{tabular}{@{}ll@{}}
\verb!'! \textit{name}  & Search for \textit{name} and leave its \\
                        & execution token (address). \verb!( -- addr )! \\
{\compileonly\verb![']!} \textit{name}  & Search for \textit{name} and compile \\
                          & it's execution token. \verb!( -- )! \\
\verb!execute!  & Execute word at address. \verb!( addr -- )! \\
                & The actual stack effect will depend on \\ 
                & the word executed. \\
\verb!@ex!  & Fetch vector from addr and execute. \\
            & \verb!( addr -- )! \\
\verb!defer! \textit{vec-name}  & Define a deferred execution vector. \verb!( -- )! \\
\verb!is! \textit{vec-name}  & Store execution token in \textit{vec-name}. \\
                             & \verb!( addr -- )! \\
\textit{vec-name}  & Execute the word whose execution token \\
               & is stored in \textit{vec-name}'s data space. \\
\verb?int!? & Store interrupt vector to table. \\
            & \verb!( xt vector-no -- )! \\
            & PIC18: \verb!vector-no! is dummy vector number (0) \\
            & for high priority interrupts. \\
            & PIC30: Alternate interrupt vector table in Flash. \\
            & PIC33: Alternate interrupt vector table in RAM. \\
            & PIC24H: Alternate interrupt vector table in RAM. \\
            & PIC24F: Alternate interrupt vector table in RAM. \\
            & PIC24FK: Alternate interrupt vector table in Flash. \\
            & PIC24E: Main interrupt vector table in RAM. \\
            & ATmega: Interrupt vector table in RAM. \\
\verb!int/! & Restore the original vector to the interrupt vector \\
            & table in flash. PIC30 PIC24FK \verb!( vector-no -- )! \\
\verb!ivt!  & Activate the normal interrupt vector table. \verb!( -- )! \\
            & Not PIC24E, dsPIC33E. \\
\verb!aivt! & Activate the alternate interrupt vector table. \verb!( -- )! \\
\end{tabular}\\


## Autostart example

\begin{tabular}{@{}ll@{}}
\verb!' my-app is turnkey!  & Autostart my-app. \\
\verb!false is turnkey!  & Disable turnkey application. \\
\end{tabular}\\


## Interrupt example

\begin{tabular}{@{}ll@{}}
\verb!ram variable icnt1!       & ...from FF source. \\
\verb!: irq_forth!              & It's a Forth colon definition \\
\verb!  [i!                     & ...in the Forth interrupt context. \\
\verb!    icnt1 @ 1+!           & \\
\verb?    icnt1 !?              & \\
\verb!  ]i!                     & \\
\verb!;i!                       & \\
\verb?' irq_forth 0 int!?       & Set the user interrupt vector. \\
\verb! !                        & \\
\verb!: init !                  & Alternatively, compile a word \\
\verb?  ['] irq_forth 0 int!?   & ...so that we can install the \\
\verb!;!                        & ...interrupt service function \\
\verb!' init is turnkey!        & ...at every warm start. \\
\end{tabular}\\


# The P register

The P register can be used as a variable or as a pointer. 
It can be used in conjunction with \verb!for!..\verb!next! 
or at any other time.\\
\begin{tabular}{@{}ll@{}}
\verb?!p?  & Store address to P(ointer) register. \verb!( addr -- )! \\
\verb!@p!  & Fetch the P register to the stack. \verb!( -- addr )! \\
{\compileonly\verb?!p>r?}  & Push contents of P to return stack and \\
             & store new address to P. \verb!( addr -- ) ( R: -- addr )! \\
{\compileonly\verb!r>p!}  & Pop from return stack to P register. \verb!( R: addr -- )! \\ 
\verb!p+! & Increment P register by one. \verb!( -- )! \\
\verb!p2+!  & Add 2 to P register. \verb!( -- )! \\
\verb!p++!  & Add n to the p register. \verb!( n -- )! \\
\verb?p!?  & Store x to the location pointed to \\
           & by the p register. \verb!( x -- )! \\
\verb!pc!!  & Store c to the location pointed to \\
            & by the p register. \verb!( c -- )! \\
\verb!p@!  & Fetch the cell pointed to \\
           & by the p register. \verb!( -- x )! \\
\verb!pc@!  & Fetch the char pointed to \\ 
            & by the p register. \verb!( -- c )! \\
\end{tabular}\\
In a definition, \verb?!p>r? and \verb!r>p! should always be used 
to allow proper nesting of words.

\bigskip

# Characters

\begin{tabular}{@{}ll@{}}
\verb!digit?!  & Convert char to a digit according to base. \\
               & \verb!( c -- n f )! \\
\verb!digit!   & Convert n to ascii character value. \verb!( n -- c )! \\
\verb!>pr!     & Convert  a character to an ASCII value. \verb!( c -- c )! \\
               & Nongraphic characters converted to a dot. \\
\verb!char! \textit{char} & Parse a character and leave ASCII value. \verb!( -- n )! \\
                          & For example: \verb!char A!  \verb!( -- 65 )! \\
{\compileonly\verb![char]!} \textit{char} & Compile inline ASCII character. \verb!( -- )! \\
\end{tabular}

\medskip

## Strings

Some of these words come from \verb!core.txt!.

\begin{tabular}{@{}ll@{}}
{\compileonly\verb!s" !} \textit{text}\verb!"! & Compile string into flash. \verb!( -- )! \\
                                 & At run time, leaves address and length. \\
                                 & \verb!( -- addr u )! \\
{\compileonly\verb!." !} \textit{text}\verb!"! & Compile string to print into flash. \verb!( -- )! \\
\verb!place! & Place string from a1 to a2 \\
             & as a counted string. \verb!( addr1 u addr2 -- )! \\
% \verb!count! & Leave the address and length of text portion \\
%              & of a counted string \verb!( addr1 -- addr2 n )! \\
\verb!n=!  & Compare strings in RAM(\verb!addr!) and Flash(\verb!nfa!). \\
           & Leave true if strings match, \verb!n < 16!. \\
           &  \verb!( addr nfa u -- f )! \\
\verb!scan! & Scan string until \verb!c! is found. \\
            & \verb!c-addr! must point to RAM and \verb!u < 255!.\\
            & \verb!( c-addr u c -- caddr1 u1 )! \\
\verb!skip! & Skip chars until \verb!c! not found. \\
            & \verb!c-addr! must point to RAM and \verb!u < 255!.\\
            & \verb!( c-addr u c -- caddr1 u1 )! \\
\verb!/string!  & Trim string. \verb!( addr u n -- addr+n u-n )! \\
\verb!>number!  & Convert string to a number. \\
                & \verb!( 0 0 addr1 u1 -- ud.l ud.h addr2 u2 )! \\
\verb!number?!  & Convert string to a number and flag. \\
                & \verb!( addr1 -- addr2 0 | n 1 | d.l d.h 2 )! \\
                & Prefix: \verb!#! decimal, \verb!$! hexadecimal, \verb!%! binary.\\
\verb!sign?!  & Get optional minus sign. \\
              & \verb!( addr1 n1 -- addr2 n2 flag )!\\
\verb!type!  & Type line to terminal, \verb!u < #256!. \verb!( addr u -- )! \\
\verb!accept! & Get line from the terminal. \verb!( c-addr +n1 -- +n2 )! \\
              & At most n1 characters are accepted, until the line \\
              & is terminated with a carriage return. \\
\verb!source! & Leave address of input buffer and number of \\
              & characters.  \verb!( -- c-addr u )! \\
\verb!evaluate! & Interpret a string in SRAM. \verb!( addr n -- )! \\
\verb!interpret! & Interpret the buffer. \verb!( c-addr u -- )! \\
\verb!parse! & Parse a word in TIB. \verb!( c -- addr length )! \\
\verb!word! & Parse a word in TIB and write length into TIB. \\
            & Leave the address of length byte on the stack. \\
            & \verb!( c -- c-addr )! \\
\end{tabular}

## Pictured numeric output

Formatted string representing an unigned double-precision integer 
is constructed in the end of \verb!tib!.\\
\begin{tabular}{@{}ll@{}}
{\compileonly\verb!<#!}  & Begin conversion to formatted string. \verb!( -- )! \\
{\compileonly\verb!#!}  & Convert 1 digit to formatted string. \verb!( ud1 -- ud2 )! \\
{\compileonly\verb!#s!}  & Convert remaining digits. \verb!( ud1 -- ud2 )! \\
           & Note that \verb!ud2! will be zero. \\
{\compileonly\verb!hold!}  & Append char to formatted string. \verb!( c -- )! \\
\verb!sign!  & Add minus sign to formatted string, if \verb!n<0!. \verb!( n -- )! \\
{\compileonly\verb!#>!}  & End conversion, leave address and count \\
           & of formatted string. \verb!( ud1 -- c-addr u )! \\
\end{tabular}\\
For example, the following:\\
\verb!-1 34. <# # # #s rot sign #> type! \\
results in \verb!-034 ok!


# Interaction with the operator

Interaction with the user is via a serial communications port, typically UART1.  
Settings are 38400\,baud, 8N1, using Xon/Xoff handshaking. 
Which particular serial port is selected is determined by the
vectors \verb!'emit!, \verb!'key! and \verb!'key?!.\\

\begin{tabular}{@{}ll@{}}
\verb!emit!  & Emit c to the serial port FIFO. \verb!( c -- )! \\
             & FIFO is 46 chars. Executes pause. \\
\verb!space!  & Emit one space character. \verb!( -- )! \\
\verb!spaces!  & Emit n space characters. \verb!( n -- )! \\
\verb!cr!  & Emit carriage-return, line-feed. \verb!( -- )! \\
\verb!key!  & Get a character from the serial port FIFO. \\
            & Execute pause until a character is available. \verb!( -- c )! \\
\verb!key?!  & Leave true if character is waiting \\
             & in the serial port FIFO.  \verb!( -- f )! \\
\end{tabular}


## Serial communication ports

\begin{tabular}{@{}ll@{}}
\verb!tx0!  & Send a character via UART0 on ATmega. \verb!( c -- )! \\
\verb!rx0!  & Receive a character from UART0 on ATmega. \verb!( -- c )! \\
\verb!rx0?!  & Leave \verb!true! if the UART0 receive buffer \\
             & is not empty. ATmega \verb!( -- f )! \\
\verb!u0-!  & Disable flow control for UART1 interface. \verb!( -- )! \\
\verb!u0+!  & Enable flow control for UART1 interface, default. \verb!( -- )! \\
\verb!tx1!  & Send character to UART1. \verb!( c -- )! \\
            & Buffered via an interrupt driven queue. \\
\verb!rx1!  & Receive a character from UART1. \verb!( -- c )! \\
            & Buffered by an interrupt-driven queue. \\
\verb!rx1?!  & Leave \verb!true! if the UART1 receive buffer \\
             & is not empty. \verb!( -- f )! \\
\verb!u1-!  & Disable flow control for UART1 interface. \verb!( -- )! \\
\verb!u1+!  & Enable flow control for UART1 interface, default. \verb!( -- )! \\
\verb!tx2!  & Send character to UART2. \verb!( c -- )! \\
            & PIC24-30-33 \\
\verb!rx2!  & Receive a character from UART2. \verb!( -- c )! \\
            & PIC24-30-33 \\
\verb!rx2?!  & Leave \verb!true! if the UART1 receive buffer \\
             & is not empty. PIC24-30-33 \verb!( -- f )! \\
\verb!u2-!  & Disable flow control for UART2 interface. \verb!( -- )! \\
\verb!u2+!  & Enable flow control for UART2 interface, default. \verb!( -- )! \\
\verb!txu!  & Send a character via the USB UART. \verb!( c -- )! \\
            & PIC18-USB \\
\verb!rxu!  & Receive a character from the USB UART. \verb!( -- c )! \\
            & PIC18-USB \\
\verb!rxu?!  & Leave \verb!true! if the USB UART receive buffer \\
             & is not empty. PIC18-USB \verb!( -- f )! \\
\end{tabular}\\


## Character queues on PIC24-30-33

\begin{tabular}{@{}ll@{}}
\verb!cq:! \textit{name} & Create character queue. \verb!( u -- )! \\
\verb!cq0! & Initialize or reset queue. \verb!( queue-addr -- )! \\
\verb!>cq?! & Is there space available in queue. \verb!( queue-addr -- f )! \\
\verb!>cq! & Put character into queue. \verb!( c queue-addr -- )! \\
\verb!cq>?! & Number of characters in queue. \verb!( queue-addr -- u )! \\
\verb!cq>! & Get character from queue. \verb!( queue-addr -- c )! \\
\verb!u1rxq! & Leave UART1 RX queue address. \verb!( -- queue-addr )! \\
\verb!u1txq! & Leave UART1 TX queue address. \verb!( -- queue-addr )! \\
\verb!u2rxq! & Leave UART2 RX queue address. \verb!( -- queue-addr )! \\
\verb!u2txq! & Leave UART2 TX queue address. \verb!( -- queue-addr )! \\
\end{tabular}\\


## Other Hardware

\begin{tabular}{@{}ll@{}}
\verb!cwd! & Clear the WatchDog counter. \verb!( -- )! \\
           & PIC18, PIC24-30-33 \\ 
\verb!ei!  & Enable interrupts. \verb!( -- )! \\
\verb!di!  & Disable interrupts. \verb!( -- )! \\
\verb!ms!  & Pause for +n milliseconds. \verb!( +n -- )! \\
\verb!ticks!  & System ticks, 0--ffff milliseconds. \verb!( -- u )! \\
\end{tabular}


# Multitasking

Load the words for multitasking from \verb!task.txt!.

\begin{tabular}{@{}ll@{}}
\verb!task:! & Define a new task in flash memory space \\
             & \verb!( tibsize stacksize rstacksize addsize -- )! \\
             & Use \verb!ram xxx allot! to leave space for the PAD \\
             & of the prevously defined task. \\
             & The OPERATOR task does not use PAD.\\
\verb!tinit! & Initialise a user area and link it \\
             & to the task loop. \verb!( taskloop-addr task-addr -- )! \\
             & Note that this may only be executed from \\
             & the operator task. \\
\verb!task!  & Leave the address of the task definition table. \verb!( -- addr )! \\
\verb!run!  & Makes a task run by inserting it after operator \\
            & in the round-robin linked list. \verb!( task-addr -- )! \\
            & May only be executed from the operator task. \\
\verb!end!  & Remove a task from the task list. \verb!( task-addr -- )! \\
            & May only be executed from the operator task. \\
\verb!single!  & End all tasks except the operator task. \verb!( -- )! \\
               & Removes all tasks from the task list. \\
               & May only be executed from the operator task. \\
\verb!tasks!  & List all running tasks. \verb!( -- )! \\
\verb!pause!  & Switch to the next task in the round robin task list. \\
              & Idle in the operator task if allowed by all tasks. \verb!( -- )! \\
\verb!his!  & Access user variables of other task. \\
            & \verb!( task.addr vvar.addr -- addr )! \\
\verb!load!  & Leave the CPU load on the stack. \verb!( -- n )! \\
             & Load is percentage of time that the CPU is busy. \\
             & Updated every 256 milliseconds. \\
\verb!load+! & Enable the load LED on AVR8. \verb!( -- )! \\
\verb!load-! & Disable the load LED on AVR8. \verb!( -- )! \\
\verb!busy!  & CPU idle mode not allowed. \verb!( -- )! \\
\verb!idle!  & CPU idle is allowed. \verb!( -- )! \\
\verb!operator!  & Leave the address of the operator task. \verb!( -- addr )! \\
\verb!ulink!  & Link to next task. \verb!( -- addr )! \\
\end{tabular}

\bigskip

# Structured Assembler

To use many of the words listed in the following sections, load the text file \verb!asm.txt!.
The assembler for each processor family provides the same set of structured flow control words,
however, the conditionals that go with these words are somewhat processor-specific.\\
\begin{tabular}{@{}ll@{}}
\verb!if,! \textit{xxx} \verb!else,! \textit{yyy} \verb!then,! & Conditional execution. \verb!( cc -- )! \\
\verb!begin,! \textit{xxx} \verb!again,! & Loop indefinitely. \verb!( -- )! \\
\verb!begin,! \textit{xxx} \textit{cc} \verb!until,! & Loop until condion is true. \verb!( -- )! \\
\end{tabular}


# Assembler words for PIC18

In the stack-effect notaion for the PIC18 family, 
f is a file register address, 
d is the result destination, 
a is the access bank modifier, 
and k is a literal value.


## Conditions for structured flow control

\begin{tabular}{@{}ll@{}}
\verb!cc,! & test carry \verb!( -- cc )! \\
\verb!nc,! & test not carry \verb!( -- cc )! \\
\verb!mi,! & test negative \verb!( -- cc )! \\
\verb!pl,! & test not negative \verb!( -- cc )! \\
\verb!z,! & test zero \verb!( -- cc )! \\
\verb!nz,! & test not zero \verb!( -- cc )! \\
\verb!ov,! & test overflow \verb!( -- cc )! \\
\verb!nov,! & test not overflow \verb!( -- cc )! \\
\verb!not,! & invert condition \verb!( cc -- not-cc )! \\
\end{tabular}

\medskip

## Destination and access modifiers

\begin{tabular}{@{}ll@{}}
\verb!w,! & Destination WREG \verb!( -- 0 )! \\
\verb!f,! & Destination file \verb!( -- 1 )! \\
\verb!a,! & Access bank \verb!( -- 0 )! \\
\verb!b,! & Use bank-select register \verb!( -- 1 )! \\
\end{tabular}


## Byte-oriented file register operations

\begin{tabular}{@{}ll@{}}
\verb!addwf,!  & Add WREG and f. \verb!( f d a -- )! \\
\verb!addwfc,!  & Add WREG and carry bit to f. \verb!( f d a -- )! \\
\verb!andwf,!  & AND WREG with f. \verb!( f d a -- )! \\
\verb!clrf,!  & Clear f. \verb!( f a -- )! \\
\verb!comf,!  & Complement f. \verb!( f d a -- )! \\
\verb!cpfseq,!  & Compare f with WREG, skip if equal. \verb!( f a -- )! \\
\verb!cpfsgt,!  & Compare f with WREG, skip if greater than. \verb!( f a -- )! \\
\verb!cpfslt,!  & Compare f with WREG, skip if less than. \verb!( f a -- )! \\
\verb!decf,!  & Decrement f. \verb!( f d a -- )! \\
\verb!decfsz,!  & Decrement f, skip if zero. \verb!( f d a -- )! \\
\verb!dcfsnz,!  & Decrement f, skip if not zero. \verb!( f d a -- )! \\
\verb!incf,!  & Increment f. \verb!( f d a -- )! \\
\verb!incfsz,!  & Increment f, skip if zero. \verb!( f d a -- )! \\
\verb!infsnz,!  & Increment f, skip if not zero. \verb!( f d a -- )! \\
\verb!iorwf,!  & Inclusive OR WREG with f. \verb!( f d a -- )! \\
\verb!movf,! & Move f. \verb!( f d a -- )! \\
\verb!movff,! & Move fs to fd. \verb!( fs fd -- )! \\
\verb!movwf,!  & Move WREG to f. \verb!( f a -- )! \\
\verb!mulwf,!  & Multiply WREG with f. \verb!( f a -- )! \\
\verb!negf,!  & Negate f. \verb!( f a -- )! \\
\verb!rlcf,!  & Rotate left f, through carry. \verb!( f d a -- )! \\
\verb!rlncf,!  & Rotate left f, no carry. \verb!( f d a -- )! \\
\verb!rrcf,!  & Rotate right f, through carry. \verb!( f d a -- )! \\
\verb!rrncf,!  & Rotate right f, no carry. \verb!( f d a -- )! \\
\verb!setf,!  & Set f. \verb!( f d a -- )! \\
\verb!subfwb,!  & Subtract f from WREG, with borrow. \verb!( f d a -- )! \\
\verb!subwf,!  & Subtract WREG from f. \verb!( f d a -- )! \\
\verb!subwfb,!  & Subtract WREG from f, with borrow. \verb!( f d a -- )! \\
\verb!swapf,!  & Swap nibbles in f. \verb!( f d a -- )! \\
\verb!tstfsz,!  & Test f, skip if zero. \verb!( f a -- )! \\
\verb!xorwf,!  & Exclusive OR WREG with f. \verb!( f d a -- )! \\
\end{tabular}


## Bit-oriented file register operations

\begin{tabular}{@{}ll@{}}
\verb!bcf,! & Bit clear f. \verb!( f b a -- )! \\
\verb!bsf,! & Bit set f. \verb!( f b a -- )! \\
\verb!btfsc,! & Bit test f, skip if clear. \verb!( f b a -- )! \\
\verb!btfss,! & Bit test f, skip if set. \verb!( f b a -- )! \\
\verb!btg,!  & Bit toggle f. \verb!( f b a -- )! \\
\end{tabular}


## Literal operations

\begin{tabular}{@{}ll@{}}
\verb!addlw,!  & Add literal and WREG. \verb!( k -- )! \\
\verb!andlw,!  & AND literal with WREG. \verb!( k -- )! \\
\verb!daw,!  & Decimal adjust packed BCD digits in WREG. \verb!( -- )! \\
\verb!iorlw,!  & Inclusive OR literal with WREG. \verb!( k -- )! \\
\verb!lfsr,!  & Move literal to FSRx. \verb!( k f -- )! \\
\verb!movlb,!  & Move literal to BSR. \verb!( k -- )! \\
\verb!movlw,!  & Move literal to WREG. \verb!( k -- )! \\
\verb!mullw,!  & Multiply literal with WREG. \verb!( k -- )! \\
\verb!sublw,!  & Subtract WREG from literal. \verb!( k -- )! \\
\verb!xorlw,!  & Exclusive OR literal with WREG. \verb!( k -- )! \\
\end{tabular}


## Data memory -- program memory operations

\begin{tabular}{@{}ll@{}}
\verb!tblrd*,!  & Table read. \verb!( -- )! \\
\verb!tblrd*+,!  & Table read with post-increment. \verb!( -- )! \\
\verb!tblrd*-,!  & Table read with post-decrement. \verb!( -- )! \\
\verb!tblrd+*,!  & Table read with pre-increment. \verb!( -- )! \\
\verb!tblwt*,!  & Table write. \verb!( -- )! \\
\verb!tblwt*+,!  & Table write with post-increment. \verb!( -- )! \\
\verb!tblwt*-,!  & Table write with post-decrement. \verb!( -- )! \\
\verb!tblwt+*,!  & Table write with pre-increment. \verb!( -- )! \\
\end{tabular}

\medskip

## Low-level flow control operations

\begin{tabular}{@{}ll@{}}
\verb!bra,! & Branch unconditionally. \verb!( rel-addr -- )! \\
\verb!call,! & Call subroutine. \verb!( addr -- )! \\
\verb!goto,!  & Go to address. \verb!( addr -- )! \\
\verb!pop,!  & Pop (discard) top of return stack. \verb!( -- )! \\
\verb!push,!  & Push address of next instruction to \\
              & top of return stack. \verb!( -- )! \\
\verb!rcall,!  & Relative call. \verb!( rel-addr -- )! \\
\verb!retfie,!  & Return from interrupt enable. \verb!( -- )! \\
\verb!retlw,!  & Return with literal in WREG. \verb!( k -- )! \\
\verb!return,!  & Return from subroutine. \verb!( -- )! \\
\end{tabular}


## Other MCU control operations

\begin{tabular}{@{}ll@{}}
\verb!clrwdt,!  & Clear watchdog timer. \verb!( -- )! \\
\verb!nop,!  & No operation. \verb!( -- )! \\
\verb!reset,!  & Software device reset. \verb!( -- )! \\
\verb!sleep,!  & Go into standby mode. \verb!( -- )! \\
\end{tabular}


# Assembler words for PIC24-30-33
As stated in the \verb!wordsAll.txt!, 
there is only a partial set of words for these families of microcontrollers.


## Conditions for structured flow control

\begin{tabular}{@{}ll@{}}
\verb!z,! & test zero \verb!( -- cc )! \\
\verb!nz,! & test not zero \verb!( -- cc )! \\
\verb!not,! & invert condition \verb!( cc -- not-cc )! \\
\end{tabular}


## Low-level flow control operations

\begin{tabular}{@{}ll@{}}
\verb!bra,! & Branch unconditionally. \verb!( rel-addr -- )! \\
\verb!rcall,! & Call subroutine. \verb!( rel-addr -- )! \\
\verb!return,!  & Return from subroutine. \verb!( -- )! \\
\verb!retfie,!  & Return from interrupt enable. \verb!( -- )! \\
\end{tabular}

\medskip

## Bit-oriented operations

\begin{tabular}{@{}ll@{}}
\verb!bclr,! & Bit clear. \verb!( bit ram-addr -- )! \\
\verb!bset,! & Bit set. \verb!( bit ram-addr -- )! \\
\verb!btst,! & Bit test to z. \verb!( bit ram-addr -- )! \\
\verb!btsc,! & Bit test, skip if clear. \verb!( bit ram-addr -- )! \\
\verb!btss,! & Bit test, skip if set. \verb!( bit ram-addr -- )! \\
\end{tabular}


# Assembler words for AVR8

For the ATmega instructions, 
\verb!Rd! denotes the destination (and source) register,
\verb!Rr! denotes the source register, 
\verb!Rw! denotes a register-pair code,
\verb!K! denotes constant data,
\verb!k! is a constant address, \verb!b! is a bit in the register,
\verb!x,Y,Z! are indirect address registers, \verb!A! is an I/O location address,
and \verb!q! is a displacement (6-bit) for direct addressing. 

\medskip

## Conditions for structured flow control

\begin{tabular}{@{}ll@{}}
\verb!cs,! & carry set \verb!( -- cc )! \\
\verb!eq,! & zero \verb!( -- cc )! \\
\verb!hs,! & half carry set \verb!( -- cc )! \\
\verb!ie,! & interrupt enabled \verb!( -- cc )! \\
\verb!lo,! & lower \verb!( -- cc )! \\
\verb!lt,! & less than \verb!( -- cc )! \\
\verb!mi,! & negative \verb!( -- cc )! \\
\verb!ts,! & T flag set \verb!( -- cc )! \\
\verb!vs,! & no overflow \verb!( -- cc )! \\
\verb!not,! & invert condition \verb!( cc -- not-cc )! \\
\end{tabular}


## Register constants

\begin{tabular}{@{}ll@{}}
\verb!Z!  & \verb!( -- 0 )! \\
\verb!Z+! & \verb!( -- 1 )! \\
\verb!-Z! & \verb!( -- 2 )! \\
\verb!Y!  & \verb!( -- 8 )! \\
\verb!Y+! & \verb!( -- 9 )! \\
\verb!-Y! & \verb!( -- 10 )! \\
\verb!X!  & \verb!( -- 12 )! \\
\verb!X+! & \verb!( -- 13 )! \\
\verb!-X! & \verb!( -- 14 )! \\
\verb!XH:XL! & \verb!( -- 01 )! \\
\verb!YH:YL! & \verb!( -- 02 )! \\
\verb!ZH:ZL! & \verb!( -- 03 )! \\
\verb!R0! & \verb!( -- 0 )! & \verb!R16! & \verb!( -- 16 )! \\
\verb!R1! & \verb!( -- 1 )! & \verb!R17! & \verb!( -- 17 )! \\
\verb!R2! & \verb!( -- 2 )! & \verb!R18! & \verb!( -- 18 )! \\
\verb!R3! & \verb!( -- 3 )! & \verb!R19! & \verb!( -- 19 )! \\
\verb!R4! & \verb!( -- 4 )! & \verb!R20! & \verb!( -- 20 )! \\
\verb!R5! & \verb!( -- 5 )! & \verb!R21! & \verb!( -- 21 )! \\
\verb!R6! & \verb!( -- 6 )! & \verb!R22! & \verb!( -- 22 )! \\
\verb!R7! & \verb!( -- 7 )! & \verb!R23! & \verb!( -- 23 )! \\
\verb!R8! & \verb!( -- 8 )! & \verb!R24! & \verb!( -- 24 )! \\
\verb!R9! & \verb!( -- 9 )! & \verb!R25! & \verb!( -- 25 )! \\
\verb!R10! & \verb!( -- 10 )! & \verb!R26! & \verb!( -- 26 )! \\
\verb!R11! & \verb!( -- 11 )! & \verb!R27! & \verb!( -- 27 )! \\
\verb!R12! & \verb!( -- 12 )! & \verb!R28! & \verb!( -- 28 )! \\
\verb!R13! & \verb!( -- 13 )! & \verb!R29! & \verb!( -- 29 )! \\
\verb!R14! & \verb!( -- 14 )! & \verb!R30! & \verb!( -- 30 )! \\
\verb!R15! & \verb!( -- 15 )! & \verb!R31! & \verb!( -- 31 )! \\
\end{tabular}\\


## Arithmetic and logic instructions

\begin{tabular}{@{}ll@{}}
\verb!add,! & Add without carry. \verb!( Rd Rr -- )! \\
\verb!adc,! & Add with carry. \verb!( Rd Rr -- )! \\
\verb!adiw,! & Add immediate to word. \verb!( Rw K -- )! \\
             & \verb!Rw = {XH:XL,YH:YL,ZH:ZL}! \\
\verb!sub,! & Subtract without carry. \verb!( Rd Rr -- )! \\
\verb!subi,! & Subtract immediate. \verb!( Rd K -- )! \\
\verb!sbc,! & Subtract with carry. \verb!( Rd Rr -- )! \\
\verb!sbci,! & Subtract immediate with carry. \verb!( Rd K -- )! \\
\verb!sbiw,! & Subtract immediate from word. \verb!( Rw K -- )! \\
             & \verb!Rw = {XH:XL,YH:YL,ZH:ZL}! \\
\verb!and,! & Logical AND. \verb!( Rd Rr -- )! \\
\verb!andi,! & Logical AND with immediate. \verb!( Rd K -- )! \\
\verb!or,! & Logical OR. \verb!( Rd Rr -- )! \\
\verb!ori,! & Logical OR with immediate. \verb!( Rd K -- )! \\
\verb!eor,! & Exclusive OR. \verb!( Rd Rr -- )! \\
\verb!com,! & One's complement. \verb!( Rd -- )! \\
\verb!neg,! & Two's complement. \verb!( Rd -- )! \\
\verb!sbr,! & Set bit(s) in register. \verb!( Rd K -- )! \\
\verb!cbr,! & Clear bit(s) in register. \verb!( Rd K -- )! \\
\verb!inc,! & Increment. \verb!( Rd -- )! \\
\verb!dec,! & Decrement. \verb!( Rd -- )! \\
\verb!tst,! & Test for zero or minus. \verb!( Rd -- )! \\
\verb!clr,! & Clear register. \verb!( Rd -- )! \\
\verb!ser,! & Set register. \verb!( Rd -- )! \\
\verb!mul,! & Multiply unsigned. \verb!( Rd Rr -- )! \\
\verb!muls,! & Multiply signed. \verb!( Rd Rr -- )! \\
\verb!mulsu! & Multiply signed with unsigned. \verb!( Rd Rr -- )! \\
\verb!fmul,! & Fractional multiply unsigned. \verb!( Rd Rr -- )! \\
\verb!fmuls,! & Fractional multiply signed. \verb!( Rd Rr -- )! \\
\verb!fmulsu,! & Fractional multiply signed with unsigned. \verb!( Rd Rr -- )! \\
\end{tabular}\\


## Branch instructions

\begin{tabular}{@{}ll@{}}
\verb!rjmp,! & Relative jump. \verb!( k -- )! \\
\verb!ijmp,! & Indirect jump to (Z). \verb!( -- )! \\
\verb!eijmp,! & Extended indirect jump to (Z). \verb!( -- )! \\
\verb!jmp,! & Jump. \verb!( k16 k6 -- )! \\
            & \verb!k6! is zero for a 16-bit address. \\
\end{tabular}\\
\begin{tabular}{@{}ll@{}}
\verb!rcall,! & Relative call subroutine. \verb!( k -- )! \\
\verb!icall,! & Indirect call to (Z). \verb!( -- )! \\
\verb!eicall,! & Extended indirect call to (Z). \verb!( -- )! \\
\verb!call,! & Call subroutine. \verb!( k16 k6 -- )! \\
             & \verb!k6! is zero for a 16-bit address. \\
\verb!ret,! & Subroutine return. \verb!( -- )! \\
\verb!reti,! & Interrupt return. \verb!( -- )! \\
\end{tabular}\\
\begin{tabular}{@{}ll@{}}
\verb!cpse,! & Compare, skip if equal. \verb!( Rd Rr -- )! \\
\verb!cp,! & Compare. \verb!( Rd Rr -- )! \\
\verb!cpc,! & Compare with carry. \verb!( Rd Rr -- )! \\
\verb!cpi,! & Compare with immediate. \verb!( Rd K -- )! \\
\end{tabular}\\
\begin{tabular}{@{}ll@{}}
\verb!sbrc,! & Skip if bit in register cleared. \verb!( Rr b -- )! \\
\verb!sbrs,! & Skip if bit in register set. \verb!( Rr b -- )! \\
\verb!sbic,! & Skip if bit in I/O register cleared. \verb!( A b -- )! \\
\verb!sbis,! & Skip if bit in I/O register set. \verb!( A b -- )! \\
\end{tabular}\\

## Data transfer instructions

\begin{tabular}{@{}ll@{}}
\verb!mov,! & Copy register. \verb!( Rd Rr -- )! \\
\verb!movw,! & Copy register pair. \verb!( Rd Rr -- )! \\
\verb!ldi,! & Load immediate. \verb!( Rd K -- )! \\
\verb!lds,! & Load direct from data space. \verb!( Rd K -- )! \\
\verb!ld,! & Load indirect. \verb!( Rd Rr -- )! \\
           & \verb!Rr = {X,X+,-X,Y,Y+,-Y,Z,Z+,-Z}! \\
\verb!ldd,! & Load indirect with dosplacement. \verb!( Rd Rr q -- )! \\
            & \verb!Rr = {Y,Z}! \\
\verb!sts,! & Store direct to data space. \verb!( k Rr -- )! \\
\verb!st,! & Store indirect. \verb!( Rr Rd -- )! \\
           & \verb!Rd = {X,X+,-X,Y,Y+,-Y,Z,Z+,-Z}! \\
\verb!std,! & Store indirect with displacement. \verb!( Rr Rd q -- )! \\
            & \verb!Rd={Y,Z}! \\
\verb!in,! & In from I/O location. \verb!( Rd A -- )! \\
\verb!out,! & Out to I/O location. \verb!( Rr A -- )! \\
\verb!push,! & Push register on stack. \verb!( Rr -- )! \\
\verb!pop,! & Pop register from stack. \verb!( Rd -- )! \\
\end{tabular}\\

## Bit and bit-test instructions

\begin{tabular}{@{}ll@{}}
\verb!lsl,! & Logical shift left. \verb!( Rd -- )! \\
\verb!lsr,! & Logical shift right. \verb!( Rd -- )! \\
\verb!rol,! & Rotate left through carry. \verb!( Rd -- )! \\
\verb!ror,! & Rotate right through carry. \verb!( Rd -- )! \\
\verb!asr,! & Arithmetic shift right. \verb!( Rd -- )! \\
\verb!swap,! & Swap nibbles. \verb!( Rd -- )! \\
\verb!bset,! & Flag set. \verb!( s -- )! \\
\verb!bclr,! & Flag clear. \verb!( s -- )! \\
\verb!sbi,! & Set bit in I/O register. \verb!( A b -- )! \\
\verb!cbi,! & Clear bit in I/O register. \verb!( A b -- )! \\
\verb!bst,! & Bit store from register to T. \verb!( Rr b -- )! \\
\verb!bld,! & Bit load from T to register. \verb!( Rd b -- )! \\
\verb!sec,! & Set carry. \verb!( -- )! \\
\verb!clc,! & Clear carry. \verb!( -- )! \\
\verb!sen,! & Set negative flag. \verb!( -- )! \\
\verb!cln,! & Clear negative flag. \verb!( -- )! \\
\verb!sez,! & Set zero flag. \verb!( -- )! \\
\verb!clz! & Clear zero flag. \verb!( -- )! \\
\verb!sei,! & Global interrupt enable. \verb!( -- )! \\
\verb!cli,! & Global interrupt disable. \verb!( -- )! \\
\verb!ses,! & Set signed test flag. \verb!( -- )! \\
\verb!cls,! & Clear signed test flag. \verb!( -- )! \\
\verb!sev,! & Set two's complement overflow. \verb!( -- )! \\
\verb!clv,! & Clear two-s complement overflow. \verb!( -- )! \\
\verb!set,! & Set T in SREG. \verb!( -- )! \\
\verb!clt,! & Clear T in SREG. \verb!( -- )! \\
\verb!seh,! & Set half carry flag in SREG. \verb!( -- )! \\
\verb!clh,! & Clear half carry flag in SREG. \verb!( -- )! \\
\end{tabular}

## MCU control instructions

\begin{tabular}{@{}ll@{}}
\verb!break,! & Break. \verb!( -- )! \\
\verb!nop,! & No operation. \verb!( -- )! \\
\verb!sleep,! & Sleep. \verb!( -- )! \\
\verb!wdr,! & Watchdog reset. \verb!( -- )! \\
\end{tabular}


# Synchronous serial communication

## I^2^C communications as master

The following words are available as a common set of words for PIC18FXXK22, 
PIC24FV32KX30X and ATmega328P microcontrollers.
Load them from a file with a name like \verb!i2c-base-XXXX.txt! where \verb!XXXX!
is the specific microcontroller.
\begin{tabular}{@{}ll@{}}
\verb!i2c.init!  & Initializes I$^2$C master mode, 100\,kHz clock. \\
                 & \verb!( -- ) !\\
\verb!i2c.close!  & Shut down the peripheral module. \verb!( -- )! \\ 
\verb!i2c.ping?!  & Leaves \verb!true! if the addressed slave device \\
                  & acknowledges. \verb!( 7-bit-addr -- f )! \\ 
\verb!i2c.addr.write!  & Address slave device for writing. \\
                       & Leave \verb!true! if the slave acknowledged. \\
                       & \verb!( 7-bit-addr -- f )! \\ 
\verb?i2c.c!?  & Send byte and leave \verb!ack! bit. \verb!( c -- ack )! \\
               & Note that the \verb!ack! bit will be high \\
               & if the slave device did \textit{not} acknowledge. \\
\verb!i2c-addr-read!  & Address slave device for reading. \\
                      & Leave \verb!true! if slave acknowledged. \\
                      & \verb!( 7-bit-addr -- f )! \\ 
\verb!i2c.c@.ack!  & Fetch a byte and \verb!ack! for another. \\
                   & \verb!( -- c )! \\ 
\verb!i2c.c@.nack!  & Fetch one last byte. \verb!( -- c )! \\ 
\verb!!  &  \verb!( -- )! \\ 
\end{tabular}\\

Low level words.

\begin{tabular}{@{}ll@{}}
\verb!i2c.idle?!  &  Leave \verb!true! if the I$^2$C bus is idle. \verb!( -- f )! \\ 
\verb!i2c.start!  &  Send start condition. \verb!( -- )! \\ 
\verb!i2c.rsen!  & Send restart condition. \verb!( -- )! \\ 
\verb!i2c.stop!  & Send stop condition. \verb!( -- )! \\ 
\verb!i2c.wait!  & Poll the I$^2$C hardware until the operation \\
                 & has finished. \verb!( -- )! \\ 
\verb!i2c.bus.reset!  & Clock through bits so that slave devices \\
                      & are sure to release the bus. \verb!( -- )! \\ 
\end{tabular}


## Alternate set I^2^C words for PIC18

Load these words from \verb!i2c_base.txt! for a PIC18 microcontroller.
They make use of the structured assembler for the PIC18.
\begin{tabular}{@{}ll@{}}
\verb!i2cinit!  & Initializes I$^2$C master mode, 100\,kHz clock. \verb!( -- ) !\\ 
\verb!i2cws! & Wake slave. Bit 0 is R/W bit. \verb!( slave-addr -- )! \\
             & The 7-bit I$^2$C address is in bits 7-1. \\
\verb?i2c!? & Write one byte to I$^2$C bus and wait for \verb!ACK!. \verb!( c -- )! \\
\verb!i2c@ak! & Read one byte and continue. \verb!( -- c )! \\
\verb!i2c@nak! & Read one last byte from the I$^2$C bus. \verb!( -- c )! \\
\verb!i2c-addr1! & Write 8-bit address to slave. \verb!( addr slave-addr -- )! \\
\verb!i2c-addr2! & Write 16-bit address to slave \verb!( addr slave-addr -- )! \\
\end{tabular}\\
Lower-level words.\\
\begin{tabular}{@{}ll@{}}
\verb!ssen! & Assert start condition. \verb!( -- )! \\
\verb!srsen! & Assert repeated start condition. \verb!( -- )! \\
\verb!spen! & Generate a stop condition. \verb!( -- )! \\
\verb!srcen! & Set receive enable. \verb!( -- )! \\
\verb!snoack! & Send not-acknowledge. \verb!( -- )! \\
\verb!sack! & Send acknowledge bit. \verb!( -- )! \\
\verb?sspbuf!? & Write byte to \verb!SSPBUF! and wait for \\
               & transmission. \verb!( c -- )! \\
\end{tabular}


## SPI communications as master

The following words are available as a common set of words for PIC18FXXK22, 
PIC24FV32KX30X and ATmega328P microcontrollers.
Load them from a file with a name like \verb!spiN-base-XXXX.txt! where \verb!XXXX!
is the specific microcontroller and \verb!N! identifies the particular SPI module.
Because SPI devices are so varied in their specification, you likely have to 
adjust the register settings in \verb!spi.init! to suit your particular device.
\begin{tabular}{@{}ll@{}}
\verb!spi.init!  & Initializes SPI master mode, 1\,MHz clock. \\
                 & \verb!( -- ) !\\
\verb!spi.close! & Shut down the peripheral module. \verb!( -- )! \\ 
\verb!spi.wait!  & Poll the SPI peripheral until the operation \\
                 & has finished. \verb!( -- )! \\
\verb!spi.cexch! & Send byte \verb!c1!, leave incoming byte \verb!c2! on stack. \\
                 & \verb!( c1 -- c2 )! \\
\verb!spi.csend! & Send byte \verb!c!. \verb!( c -- )! \\
\verb!spi.select! & Select the external device. \verb!( -- )! \\
\verb!spi.deselect! & Deselect the external device. \verb!( -- )! \\
\end{tabular}


[bibliography]
= Bibliography

This guide assembled by Peter Jacobs, School of Mechanical Engineering,
The University of Queensland, February-2016 as Report 2016/02.
Update 2018-04-09, Ported to ASCIIDOC 2022-01-02.

It is a remix of material from the following sources: +

* FlashForth v5.0 source code and word list by Mikael Nordman
http://flashforth.com/

* EK Conklin and ED Rather _Forth Programmer's Handbook_ 3rd Ed. 2007 FORTH, Inc.

* L Brodie _Starting Forth_ 2nd Ed., 1987 Prentice-Hall Software Series.

* Robert B. Reese _Microprocessors from Assembly Language to C Using the PIC18Fxx2_ 
Da Vinci Engineering Press, 2005.

* Microchip _16-bit MCU and DSC Programmers Reference Manual_ Document DS70157F, 2011.

* Atmel _8-bit AVR Insturction Set_ Document 08561-AVR-07/10.

