# makefile for ASCIIdoc version of the FlashForth docs
# PJ 2021-12-30

elements-of-flashforth-5.html : elements-of-flashforth-5.adoc
	asciidoctor elements-of-flashforth-5.adoc

clean :
	- rm elements-of-flashforth-5.html
